// Model for user data
// Models allow us to create a structure for our entities/attributes in out database, like a user may have an email, and username associated with them
//Model files are named with starting with an uppercase letter in common practice

// we use mongoose to allow us to have a schema-base solution to our app's data
const mongoose = require('mongoose');

// this creates a schema for our users document in our MongoDB database (a document is similar to a table in a SQL database)
// our user will have a name field that is required and is a string, an email field that is a string and is required and it must be unique so we don't have multiple users registed with the same email, we will have a password that is a string and required, and lastly we will have an avatar field that will be made up a string that is generated by Gravatar, we will also have a data field that will have a type of date that will contain the current data
const UserSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  avatar: {
    type: String,
  },
  date: {
    type: Date,
    default: Date.now,
  },
});

// we are going to export our user model using the module.exports function
// we are going to name this model User
// because we are exporting a model we are going to use mongoose.model and pass in the name of the collection and then the name of the schema
module.exports = User = mongoose.model('user', UserSchema);
